// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRDR0Qnar0vGsi2VdXbvCxZ8RlW5hmKcs',
    appId: '1:879209971125:web:9c230108cd17837d22adfc',
    messagingSenderId: '879209971125',
    projectId: 'color-kingdom',
    authDomain: 'color-kingdom.firebaseapp.com',
    storageBucket: 'color-kingdom.firebasestorage.app',
    measurementId: 'G-SQP07W070D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2NtoaZJZe3nVYg1xjoo38RhruXzkLBc',
    appId: '1:879209971125:android:f6778d25215eff3122adfc',
    messagingSenderId: '879209971125',
    projectId: 'color-kingdom',
    storageBucket: 'color-kingdom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOmeHUSItD8tgwHOIaryjBEFDqHysZdzU',
    appId: '1:879209971125:ios:4b31f48d7eff912622adfc',
    messagingSenderId: '879209971125',
    projectId: 'color-kingdom',
    storageBucket: 'color-kingdom.firebasestorage.app',
    iosBundleId: 'com.example.colorKingdom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOmeHUSItD8tgwHOIaryjBEFDqHysZdzU',
    appId: '1:879209971125:ios:4b31f48d7eff912622adfc',
    messagingSenderId: '879209971125',
    projectId: 'color-kingdom',
    storageBucket: 'color-kingdom.firebasestorage.app',
    iosBundleId: 'com.example.colorKingdom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRDR0Qnar0vGsi2VdXbvCxZ8RlW5hmKcs',
    appId: '1:879209971125:web:c3aef2732470189622adfc',
    messagingSenderId: '879209971125',
    projectId: 'color-kingdom',
    authDomain: 'color-kingdom.firebaseapp.com',
    storageBucket: 'color-kingdom.firebasestorage.app',
    measurementId: 'G-HTLXM2PXQ8',
  );
}
